version: 2

updates:
  # Yarn dependencies
  - package-ecosystem: "npm"
    directory: "/"
    allow:
      - dependency-type: "direct"
    schedule:
      interval: "monthly"
    labels:
      - "Type: Dependencies"
    commit-message:
      prefix: "Yarn"
      include: "scope"
    reviewers:
      - "SebKay"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
